"""add section timer fields

Revision ID: 1fa0f9c766c1
Revises: 76d1c7682213
Create Date: 2026-09-03 21:19:32.807357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa0f9c766c1'
down_revision: Union[str, Sequence[str], None] = '76d1c7682213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('section_started_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('assessments', sa.Column('section_deadline', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'section_deadline')
    op.drop_column('assessments', 'section_started_at')
    # ### end Alembic commands ###
